version: '2'
services:
  redis:
    image: redis
  web:
    build: web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/code
    links:
      - redis
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links: 
      - web:web
